### PR TITLE
New realisation for thread safe history middleware

### PR DESCRIPTION
**Pull request by davydovanton**

### CODE REVIEW

**Comment by davydovanton** [comment]
@mperham I [added](https://github.com/davydovanton/sidekiq-history/pull/26/files#diff-5b317b0587c3a8da9dc23409af81ccd6R60) test for checking thread-safe in middleware. Also I used redis transaction (`watch` and `multi` methods) for fixing my history storage. What do you think, it's normal for you?

**Comment by mperham** [comment]
This is safer but it's not performant at all.  The issue is that you're still using Sidekiq.load_json to store a hash as a string rather than using Redis' native Hash commands.  You want to use something like:

```
Sidekiq.redis do |c|
  c.multi do
    c.hincrby(history_key, "runtime_ms", job_time_in_ms)
    c.hmset(history_key, "last_status", "passed", "last_runtime", Time.now.utc.to_i)
  end
end
```

Read through [the Hash commands](http://redis.io/commands#hash) and figure out what you need to do to remove `Sidekiq.load_json`.

**Comment by davydovanton** [comment]
Okay, I understood you, thanks for review! :metal:

**Comment by davydovanton** [comment]
@mperham I'll change hash serialization to native redis hash in separate PR.

**Pull request merged**
